name: Continuous Integration

on:
  push:
    branches:
      - main  
  pull_request:
    types: [opened, synchronize]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  
    
    - name: Test project
      run: npm test
